ALTER TYPE "ProjectStage" ADD VALUE IF NOT EXISTS 'CONTACT';
ALTER TYPE "ProjectStage" ADD VALUE IF NOT EXISTS 'DESIGN';
ALTER TYPE "ProjectStage" ADD VALUE IF NOT EXISTS 'PRODUCTION';
ALTER TYPE "ProjectStage" ADD VALUE IF NOT EXISTS 'CLOSED';
ALTER TYPE "ProjectStage" ADD VALUE IF NOT EXISTS 'BILLED';
ALTER TYPE "ProjectStage" ADD VALUE IF NOT EXISTS 'WRAP_UP';
ALTER TYPE "ProjectStage" ADD VALUE IF NOT EXISTS 'LOST';
