ALTER TYPE "CustomerType" ADD VALUE IF NOT EXISTS 'LONGMEI_STORE';
ALTER TYPE "CustomerType" ADD VALUE IF NOT EXISTS 'CABINET_FACTORY';
ALTER TYPE "CustomerType" ADD VALUE IF NOT EXISTS 'DESIGN_COMPANY';
ALTER TYPE "CustomerType" ADD VALUE IF NOT EXISTS 'DEALER_COMPANY';
ALTER TYPE "CustomerType" ADD VALUE IF NOT EXISTS 'CONSTRUCTION';
ALTER TYPE "CustomerType" ADD VALUE IF NOT EXISTS 'LABOR_MATERIAL';
ALTER TYPE "CustomerType" ADD VALUE IF NOT EXISTS 'INDIVIDUAL';